name: 'Deploy "Project CRM" to Production Environment on Laravel Forge'

on:
  push:
    branches:
      - main

jobs:
  forge-deploy:
    name: 'Laravel Forge Deploy'
    runs-on: ubuntu-latest

    steps:
      # Trigger Laravel Forge Deploy
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.PRODUCTION_TRIGGER_URL }}
